org.gradle.jvmargs=-Xmx2G

enabledPlatforms=fabric,neoforge

version=2.0.0-alpha.5
group=earth.terrarium.cadmus

minecraftVersion=1.21
parchmentVersion=2024.07.28

resourcefulLibVersion=3.0.12

reiVersion=16.0.754
journeymapVersion=1.21.1-6.0.0-beta.39
journeymapApiVersion=2.0.0-1.21-SNAPSHOT
commonNetworkneoforgeVersion=QYLtKTFr
commonNetworkfabricVersion=JfV4uInx
prometheusVersion=2.0.0