org.gradle.jvmargs=-Xmx2G

enabledPlatforms=fabric,neoforge

version=2.0.0-alpha.6
group=earth.terrarium.cadmus

minecraftVersion=1.21
minecraftVersionFull=1.21.1
parchmentVersion=2024.07.28

# Libraries
resourcefulLibVersion=3.0.12
olympusVersion=1.0.13
commonatsVersion=2.0
byteCodecsVersion=1.0.2

# Mod Compatibility
prometheusVersion=2.0.0
reiVersion=16.0.799
journeymapVersion=6.0.0-beta.52
journeymapApiVersion=2.0.0-1.21-SNAPSHOT
xaerosWorldMapVersion=1.39.0
xaerosMiniMapVersion=24.3.0

# Misc
commonNetworkneoforgeVersion=QYLtKTFr
commonNetworkfabricVersion=JfV4uInx